const popularSkills = [
    "Leadership",
    "Team Building",
    "Problem Solving",
    "HTML",
    "CSS",
    "JavaScript",
    "MongoDB",
    "React",
    "Express",
    "Node.js",
    "MERN Stack",
    "Angular",
    "Vue.js",
    "SQL",
    "Computer Networks",
    "Operating Systems",
    "DBMS",
    "OOP",
    "C++",
    "Java",
    "Python",
    "Machine Learning",
    "Data Structures",
    "Algorithms",
    "Git",
    "Agile",
    "RESTful APIs",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "DevOps",
    "CI/CD",
    "TypeScript",
    "GraphQL",
    "Redux",
    "Sass",
    "Webpack",
    "Babel",
    "Jest",
    "Mocha",
]

export default popularSkills;